---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Install additional packages
      package:
        name: "{{ packages }}"
      vars:
        packages:
        - iperf3
        - ntp
