- hosts: all:!localhost
  become: true
  gather_facts: true
  tasks:
  - name: Do OS update
    package:
      name: "*"
      state: latest

  - block:
    - name: Check if reboot needed for RedHat
      shell: needs-restarting -r
      failed_when: false
      changed_when: false
      register: reboot_required
    - name: Rebooting RedHat
      reboot:
      when: reboot_required.rc != 0
    when: ansible_facts['os_family'] == "RedHat"

  - block:
    - name: Check if reboot needed for Debian
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Rebooting Debian
      reboot:
      when: reboot_required.stat.exists
    when: ansible_facts['os_family'] == "Debian"
